-- exam_content.sqlite — bundled read-only content DB.
-- Generated by tools/seed/seed.py. Do not edit the .sqlite directly;
-- edit CSVs in tools/seed/sample/ and rerun seed.py.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS licenses (
  id       INTEGER PRIMARY KEY,
  code     TEXT UNIQUE NOT NULL,     -- 'car' | 'motorcycle' | 'cdl'
  name     TEXT NOT NULL,
  icon     TEXT
);

CREATE TABLE IF NOT EXISTS states (
  id   INTEGER PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,          -- 'CA', 'TX', ...
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
  id         INTEGER PRIMARY KEY,
  license_id INTEGER NOT NULL REFERENCES licenses(id),
  code       TEXT NOT NULL,           -- 'general_knowledge', 'hazmat', ...
  name       TEXT NOT NULL,
  kind       TEXT NOT NULL,           -- 'core' | 'endorsement'
  sort_order INTEGER DEFAULT 0,
  UNIQUE(license_id, code)
);

CREATE TABLE IF NOT EXISTS questions (
  id          INTEGER PRIMARY KEY,
  license_id  INTEGER NOT NULL REFERENCES licenses(id),
  category_id INTEGER NOT NULL REFERENCES categories(id),
  state_id    INTEGER REFERENCES states(id),        -- NULL = federal/common
  text        TEXT NOT NULL,
  explanation TEXT,
  image_name  TEXT,
  difficulty  INTEGER DEFAULT 1,                    -- 1..3
  lang        TEXT NOT NULL DEFAULT 'en'
);
CREATE INDEX IF NOT EXISTS idx_q_lookup ON questions(license_id, category_id, state_id, lang);

CREATE TABLE IF NOT EXISTS answers (
  id          INTEGER PRIMARY KEY,
  question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  text        TEXT NOT NULL,
  is_correct  INTEGER NOT NULL DEFAULT 0,
  sort_order  INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_a_q ON answers(question_id);

CREATE TABLE IF NOT EXISTS cheat_sheets (
  id          INTEGER PRIMARY KEY,
  license_id  INTEGER NOT NULL REFERENCES licenses(id),
  state_id    INTEGER REFERENCES states(id),
  title       TEXT NOT NULL,
  body_md     TEXT NOT NULL,
  cover_image TEXT,
  lang        TEXT NOT NULL DEFAULT 'en'
);

CREATE TABLE IF NOT EXISTS handbooks (
  id         INTEGER PRIMARY KEY,
  state_id   INTEGER NOT NULL REFERENCES states(id),
  license_id INTEGER NOT NULL REFERENCES licenses(id),
  title      TEXT NOT NULL,
  pdf_name   TEXT,
  body_md    TEXT,
  version    TEXT,
  lang       TEXT NOT NULL DEFAULT 'en',
  UNIQUE(state_id, license_id, lang)
);

CREATE TABLE IF NOT EXISTS exam_specs (
  id             INTEGER PRIMARY KEY,
  state_id       INTEGER NOT NULL REFERENCES states(id),
  license_id     INTEGER NOT NULL REFERENCES licenses(id),
  category_id    INTEGER REFERENCES categories(id),   -- NULL = mixed
  question_count INTEGER NOT NULL,
  pass_threshold REAL NOT NULL,                        -- 0.80 = 80%
  time_limit_sec INTEGER,
  UNIQUE(state_id, license_id, category_id)
);
